# Generated by Django 4.2.8 on 2023-12-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bins",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.TextField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "expiry_policy",
                    models.CharField(
                        choices=[("1", "1 day"), ("7", "7 days"), ("30", "30 days"), ("0", "Never")],
                        default="never",
                        max_length=7,
                    ),
                ),
                ("expires_on", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
